# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "dhp-api"
fullnameOverride: "dhp-api"

replicaCount: 1

image:
  repository: <helm-repo>
  tag: <helm-tag>
  pullSecret: regsecret
  pullPolicy: IfNotPresent
  # for local development against Minikube registry
  #pullPolicy: Never

service:
  type: ClusterIP
  externalPort: 33031
  internalPort: 3010
  ssl: disabled

configuration:
  probes: disabled
  environment: production
  issuer:
    id:
  appId:
    url:
    authServerHost:
    tenantId:
    clientId:
    clientSecret:
  session:
    secret: 
  certpath: configs/server.cert
  keypath: configs/server.key

newRelic:
  enabled: "false"
  appName: "null"
  licenseKey: "null"

ingress:
  enabled: true
  tls:
  - secretName:

cluster:
  ingress:
    enabled:
    albId:
    subdomain:
    secretName:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 200m
  #  memory: 512Mi

serviceVolumeMounts:
  - name: hpass-hpass-api-cert-volume
    mountPath: /whuser/config/tls/cert
    readOnly: true
  - name: hpass-hpass-api-key-volume
    mountPath: /whuser/config/tls/key
    readOnly: true

serviceVolumes:
  - name: hpass-hpass-api-cert-volume
    secret:
      secretName: hpass-hpass-api-cert-vol
  - name: hpass-hpass-api-key-volume
    secret:
      secretName: hpass-hpass-api-key-vol
